// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct HealthData {
  var heartRate: String? = nil
  var calories: String? = nil

  static func fromList(_ list: [Any?]) -> HealthData? {
    let heartRate: String? = nilOrValue(list[0])
    let calories: String? = nilOrValue(list[1])

    return HealthData(
      heartRate: heartRate,
      calories: calories
    )
  }
  func toList() -> [Any?] {
    return [
      heartRate,
      calories,
    ]
  }
}
private class HealthApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return HealthData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HealthApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HealthData {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HealthApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HealthApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HealthApiCodecWriter(data: data)
  }
}

class HealthApiCodec: FlutterStandardMessageCodec {
  static let shared = HealthApiCodec(readerWriter: HealthApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HealthApi {
  func updateHealthData(data: HealthData) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HealthApiSetup {
  /// The codec used by HealthApi.
  static var codec: FlutterStandardMessageCodec { HealthApiCodec.shared }
  /// Sets up an instance of `HealthApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HealthApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateHealthDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.long_covid_android_ios_pigeons_garmin_connectiq.HealthApi.updateHealthData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateHealthDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! HealthData
        do {
          try api.updateHealthData(data: dataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateHealthDataChannel.setMessageHandler(nil)
    }
  }
}
